# These are supported funding model platforms

github: sanchezcl
otechie: # Replace with asingle Otechie username
custom: ['https://www.blockchain.com/btc/address/1HuxXriPE2Bbnag3jJrqa3bkNHrs297dYH']
